using Darkmatter.Features.AppBoot.Flow;
using Darkmatter.Features.AppBoot.SceneRefs;
using Darkmatter.Libs.Installers;
using UnityEngine;
using VContainer;
using VContainer.Unity;

namespace Darkmatter.Features.AppBoot.Installers
{
    public class AppBootFeatureModule : MonoBehaviour, IModule
    {
        [SerializeField] private AppBootSceneRefs sceneRefs;

        public void Register(IContainerBuilder builder)
        {
            if (sceneRefs != null)
                builder.RegisterComponent(sceneRefs);
            builder.RegisterEntryPoint<AppBootFlow>();
        }
    }
}